export const animals = [
  {
    location: 'Kharkiv',
    isDog: true,
    sex: 'male',
    age: 1,
    type: 'Poodle Toy',
    color: 'black',
    isVaccinated: true,
    description:
      'This is a beautiful example of a Poodle Toy, known for its Mixed coat. At 1 years old, Dog 1 is vaccinated and loves to play in Ukraine.',
    images: [
      'https://images.dog.ceo/breeds/terrier-australian/n02096294_568.jpg',
      'https://images.dog.ceo/breeds/dhole/n02115913_4031.jpg',
      'https://images.dog.ceo/breeds/maltese/n02085936_3292.jpg',
    ],
    name: 'Max',
    size: 'medium',
    timeStamp: 1091633462424,
  },
  {
    location: 'Dnipro',
    isDog: false,
    sex: 'female',
    age: 2,
    type: 'Retriever Flatcoated',
    color: 'white',
    isVaccinated: false,
    description:
      'This is a beautiful example of a Retriever Flatcoated, known for its Mixed coat. At 2 years old, Dog 2 is not vaccinated and loves to play in Ukraine.',
    images: [
      'https://images.dog.ceo/breeds/dhole/n02115913_4031.jpg',
      'https://images.dog.ceo/breeds/maltese/n02085936_3292.jpg',
      'https://images.dog.ceo/breeds/pitbull/IMG_20190826_121528_876.jpg',
    ],
    name: 'Bella',
    size: 'big',
    timeStamp: 1623150570788,
  },
  {
    location: 'Lviv',
    isDog: true,
    sex: 'male',
    age: 3,
    type: 'Papillon',
    color: 'white',
    isVaccinated: true,
    description:
      'This is a beautiful example of a Papillon, known for its Mixed coat. At 3 years old, Dog 3 is vaccinated and loves to play in Ukraine.',
    images: [
      'https://images.dog.ceo/breeds/maltese/n02085936_3292.jpg',
      'https://images.dog.ceo/breeds/pitbull/IMG_20190826_121528_876.jpg',
      'https://images.dog.ceo/breeds/kelpie/n02105412_2301.jpg',
    ],
    name: 'Charlie',
    size: 'small',
    timeStamp: 1447097824272,
  },
  {
    location: 'Kharkiv',
    isDog: false,
    sex: 'female',
    age: 4,
    type: 'Mastiff English',
    color: 'brown',
    isVaccinated: false,
    description:
      'This is a beautiful example of a Mastiff English, known for its Mixed coat. At 4 years old, Dog 4 is not vaccinated and loves to play in Ukraine.',
    images: [
      'https://images.dog.ceo/breeds/pitbull/IMG_20190826_121528_876.jpg',
      'https://images.dog.ceo/breeds/kelpie/n02105412_2301.jpg',
      'https://images.dog.ceo/breeds/sharpei/noel.jpg',
    ],
    name: 'Luna',
    size: 'medium',
    timeStamp: 1340604029413,
  },
  {
    location: 'Dnipro',
    isDog: true,
    sex: 'male',
    age: 5,
    type: 'Komondor',
    color: 'mixed',
    isVaccinated: true,
    description:
      'This is a beautiful example of a Komondor, known for its Mixed coat. At 5 years old, Dog 5 is vaccinated and loves to play in Ukraine.',
    images: [
      'https://images.dog.ceo/breeds/kelpie/n02105412_2301.jpg',
      'https://images.dog.ceo/breeds/sharpei/noel.jpg',
      'https://images.dog.ceo/breeds/mastiff-tibetan/n02108551_3980.jpg',
    ],
    name: 'Cooper',
    size: 'big',
    timeStamp: 1587023116695,
  },
  {
    location: 'Kharkiv',
    isDog: false,
    sex: 'female',
    age: 6,
    type: 'Poodle Toy',
    color: 'mixed',
    isVaccinated: false,
    description:
      'This is a beautiful example of a Poodle Toy, known for its Mixed coat. At 6 years old, Dog 6 is not vaccinated and loves to play in Ukraine.',
    images: [
      'https://images.dog.ceo/breeds/sharpei/noel.jpg',
      'https://images.dog.ceo/breeds/mastiff-tibetan/n02108551_3980.jpg',
      'https://images.dog.ceo/breeds/terrier-tibetan/n02097474_3461.jpg',
    ],
    name: 'Lucy',
    size: 'small',
    timeStamp: 1006898640756,
  },
  {
    location: 'Lviv',
    isDog: true,
    sex: 'male',
    age: 7,
    type: 'Retriever Flatcoated',
    color: 'mixed',
    isVaccinated: true,
    description:
      'This is a beautiful example of a Retriever Flatcoated, known for its Mixed coat. At 7 years old, Dog 7 is vaccinated and loves to play in Ukraine.',
    images: [
      'https://images.dog.ceo/breeds/mastiff-tibetan/n02108551_3980.jpg',
      'https://images.dog.ceo/breeds/terrier-tibetan/n02097474_3461.jpg',
      'https://images.dog.ceo/breeds/finnish-lapphund/mochilamvan.jpg',
    ],
    name: 'Buddy',
    size: 'medium',
    timeStamp: 1266585971482,
  },
  {
    location: 'Kharkiv',
    isDog: false,
    sex: 'female',
    age: 8,
    type: 'Papillon',
    color: 'mixed',
    isVaccinated: false,
    description:
      'This is a beautiful example of a Papillon, known for its Mixed coat. At 8 years old, Dog 8 is not vaccinated and loves to play in Ukraine.',
    images: [
      'https://images.dog.ceo/breeds/terrier-tibetan/n02097474_3461.jpg',
      'https://images.dog.ceo/breeds/finnish-lapphund/mochilamvan.jpg',
      'https://images.dog.ceo/breeds/terrier-toy/n02087046_2152.jpg',
    ],
    name: 'Daisy',
    size: 'big',
    timeStamp: 1085972560458,
  },
  {
    location: 'Lviv',
    isDog: true,
    sex: 'male',
    age: 9,
    type: 'Mastiff English',
    color: 'white',
    isVaccinated: true,
    description:
      'This is a beautiful example of a Mastiff English, known for its Mixed coat. At 9 years old, Dog 9 is vaccinated and loves to play in Ukraine.',
    images: [
      'https://images.dog.ceo/breeds/finnish-lapphund/mochilamvan.jpg',
      'https://images.dog.ceo/breeds/terrier-toy/n02087046_2152.jpg',
      'https://images.dog.ceo/breeds/schnauzer-giant/n02097130_888.jpg',
    ],
    name: 'Rocky',
    size: 'small',
    timeStamp: 979932177283,
  },
  {
    location: 'Kiev',
    isDog: false,
    sex: 'female',
    age: 10,
    type: 'Komondor',
    color: 'black',
    isVaccinated: false,
    description:
      'This is a beautiful example of a Komondor, known for its Mixed coat. At 10 years old, Dog 10 is not vaccinated and loves to play in Ukraine.',
    images: [
      'https://images.dog.ceo/breeds/terrier-toy/n02087046_2152.jpg',
      'https://images.dog.ceo/breeds/schnauzer-giant/n02097130_888.jpg',
      'https://images.dog.ceo/breeds/hound-plott/hhh_plott002.jpg',
    ],
    name: 'Molly',
    size: 'medium',
    timeStamp: 1639415835887,
  },
  {
    location: 'Dnipro',
    isDog: true,
    sex: 'male',
    age: 1,
    type: 'Poodle Toy',
    color: 'brown',
    isVaccinated: true,
    description:
      'This is a beautiful example of a Poodle Toy, known for its Mixed coat. At 1 years old, Dog 11 is vaccinated and loves to play in Ukraine.',
    images: [
      'https://images.dog.ceo/breeds/schnauzer-giant/n02097130_888.jpg',
      'https://images.dog.ceo/breeds/hound-plott/hhh_plott002.jpg',
      'https://images.dog.ceo/breeds/sheepdog-english/n02105641_3364.jpg',
    ],
    name: 'Bear',
    size: 'big',
    timeStamp: 1254197197682,
  },
  {
    location: 'Kharkiv',
    isDog: false,
    sex: 'female',
    age: 2,
    type: 'Retriever Flatcoated',
    color: 'brown',
    isVaccinated: false,
    description:
      'This is a beautiful example of a Retriever Flatcoated, known for its Mixed coat. At 2 years old, Dog 12 is not vaccinated and loves to play in Ukraine.',
    images: [
      'https://images.dog.ceo/breeds/hound-plott/hhh_plott002.jpg',
      'https://images.dog.ceo/breeds/sheepdog-english/n02105641_3364.jpg',
      'https://images.dog.ceo/breeds/komondor/n02105505_4458.jpg',
    ],
    name: 'Sadie',
    size: 'small',
    timeStamp: 1149973787671,
  },
  {
    location: 'Dnipro',
    isDog: true,
    sex: 'male',
    age: 3,
    type: 'Papillon',
    color: 'white',
    isVaccinated: true,
    description:
      'This is a beautiful example of a Papillon, known for its Mixed coat. At 3 years old, Dog 13 is vaccinated and loves to play in Ukraine.',
    images: [
      'https://images.dog.ceo/breeds/sheepdog-english/n02105641_3364.jpg',
      'https://images.dog.ceo/breeds/komondor/n02105505_4458.jpg',
      'https://images.dog.ceo/breeds/whippet/n02091134_17638.jpg',
    ],
    name: 'Tucker',
    size: 'medium',
    timeStamp: 1095103034508,
  },
  {
    location: 'Dnipro',
    isDog: false,
    sex: 'female',
    age: 4,
    type: 'Mastiff English',
    color: 'brown',
    isVaccinated: false,
    description:
      'This is a beautiful example of a Mastiff English, known for its Mixed coat. At 4 years old, Dog 14 is not vaccinated and loves to play in Ukraine.',
    images: [
      'https://images.dog.ceo/breeds/komondor/n02105505_4458.jpg',
      'https://images.dog.ceo/breeds/whippet/n02091134_17638.jpg',
      'https://images.dog.ceo/breeds/hound-blood/n02088466_8904.jpg',
    ],
    name: 'Maggie',
    size: 'big',
    timeStamp: 1362892902276,
  },
  {
    location: 'Lviv',
    isDog: true,
    sex: 'male',
    age: 5,
    type: 'Komondor',
    color: 'brown',
    isVaccinated: true,
    description:
      'This is a beautiful example of a Komondor, known for its Mixed coat. At 5 years old, Dog 15 is vaccinated and loves to play in Ukraine.',
    images: [
      'https://images.dog.ceo/breeds/whippet/n02091134_17638.jpg',
      'https://images.dog.ceo/breeds/hound-blood/n02088466_8904.jpg',
      'https://images.dog.ceo/breeds/schnauzer-giant/n02097130_1531.jpg',
    ],
    name: 'Oliver',
    size: 'small',
    timeStamp: 1617076183670,
  },
  {
    location: 'Kiev',
    isDog: false,
    sex: 'female',
    age: 6,
    type: 'Poodle Toy',
    color: 'black',
    isVaccinated: false,
    description:
      'This is a beautiful example of a Poodle Toy, known for its Mixed coat. At 6 years old, Dog 16 is not vaccinated and loves to play in Ukraine.',
    images: [
      'https://images.dog.ceo/breeds/hound-blood/n02088466_8904.jpg',
      'https://images.dog.ceo/breeds/schnauzer-giant/n02097130_1531.jpg',
      'https://images.dog.ceo/breeds/terrier-silky/n02097658_329.jpg',
    ],
    name: 'Sophie',
    size: 'medium',
    timeStamp: 1526581070916,
  },
  {
    location: 'Dnipro',
    isDog: true,
    sex: 'male',
    age: 7,
    type: 'Retriever Flatcoated',
    color: 'mixed',
    isVaccinated: true,
    description:
      'This is a beautiful example of a Retriever Flatcoated, known for its Mixed coat. At 7 years old, Dog 17 is vaccinated and loves to play in Ukraine.',
    images: [
      'https://images.dog.ceo/breeds/schnauzer-giant/n02097130_1531.jpg',
      'https://images.dog.ceo/breeds/terrier-silky/n02097658_329.jpg',
      'https://images.dog.ceo/breeds/sheepdog-english/n02105641_7603.jpg',
    ],
    name: 'Duke',
    size: 'big',
    timeStamp: 1528729538871,
  },
  {
    location: 'Lviv',
    isDog: false,
    sex: 'female',
    age: 8,
    type: 'Papillon',
    color: 'brown',
    isVaccinated: false,
    description:
      'This is a beautiful example of a Papillon, known for its Mixed coat. At 8 years old, Dog 18 is not vaccinated and loves to play in Ukraine.',
    images: [
      'https://images.dog.ceo/breeds/terrier-silky/n02097658_329.jpg',
      'https://images.dog.ceo/breeds/sheepdog-english/n02105641_7603.jpg',
      'https://images.dog.ceo/breeds/terrier-russell/jack2.jpg',
    ],
    name: 'Chloe',
    size: 'small',
    timeStamp: 1040507285672,
  },
  {
    location: 'Lviv',
    isDog: true,
    sex: 'male',
    age: 9,
    type: 'Mastiff English',
    color: 'mixed',
    isVaccinated: true,
    description:
      'This is a beautiful example of a Mastiff English, known for its Mixed coat. At 9 years old, Dog 19 is vaccinated and loves to play in Ukraine.',
    images: [
      'https://images.dog.ceo/breeds/sheepdog-english/n02105641_7603.jpg',
      'https://images.dog.ceo/breeds/terrier-russell/jack2.jpg',
      'https://images.dog.ceo/breeds/terrier-dandie/n02096437_832.jpg',
    ],
    name: 'Riley',
    size: 'medium',
    timeStamp: 1382653805511,
  },
  {
    location: 'Dnipro',
    isDog: false,
    sex: 'female',
    age: 10,
    type: 'Komondor',
    color: 'brown',
    isVaccinated: false,
    description:
      'This is a beautiful example of a Komondor, known for its Mixed coat. At 10 years old, Dog 20 is not vaccinated and loves to play in Ukraine.',
    images: [
      'https://images.dog.ceo/breeds/terrier-russell/jack2.jpg',
      'https://images.dog.ceo/breeds/terrier-dandie/n02096437_832.jpg',
      'https://images.dog.ceo/breeds/poodle-standard/n02113799_2068.jpg',
    ],
    name: 'Bailey',
    size: 'big',
    timeStamp: 998858923965,
  },
  {
    location: 'Dnipro',
    isDog: true,
    sex: 'male',
    age: 1,
    type: 'Poodle Toy',
    color: 'brown',
    isVaccinated: true,
    description:
      'This is a beautiful example of a Poodle Toy, known for its Mixed coat. At 1 years old, Dog 21 is vaccinated and loves to play in Ukraine.',
    images: [
      'https://images.dog.ceo/breeds/terrier-dandie/n02096437_832.jpg',
      'https://images.dog.ceo/breeds/poodle-standard/n02113799_2068.jpg',
      'https://images.dog.ceo/breeds/spaniel-irish/n02102973_645.jpg',
    ],
    name: 'Toby',
    size: 'small',
    timeStamp: 1103712684480,
  },
  {
    location: 'Lviv',
    isDog: false,
    sex: 'female',
    age: 2,
    type: 'Retriever Flatcoated',
    color: 'white',
    isVaccinated: false,
    description:
      'This is a beautiful example of a Retriever Flatcoated, known for its Mixed coat. At 2 years old, Dog 22 is not vaccinated and loves to play in Ukraine.',
    images: [
      'https://images.dog.ceo/breeds/poodle-standard/n02113799_2068.jpg',
      'https://images.dog.ceo/breeds/spaniel-irish/n02102973_645.jpg',
      'https://images.dog.ceo/breeds/greyhound-italian/n02091032_102.jpg',
    ],
    name: 'Lola',
    size: 'medium',
    timeStamp: 1045827005365,
  },
  {
    location: 'Lviv',
    isDog: true,
    sex: 'male',
    age: 3,
    type: 'Papillon',
    color: 'white',
    isVaccinated: true,
    description:
      'This is a beautiful example of a Papillon, known for its Mixed coat. At 3 years old, Dog 23 is vaccinated and loves to play in Ukraine.',
    images: [
      'https://images.dog.ceo/breeds/spaniel-irish/n02102973_645.jpg',
      'https://images.dog.ceo/breeds/greyhound-italian/n02091032_102.jpg',
      'https://images.dog.ceo/breeds/terrier-irish/n02093991_89.jpg',
    ],
    name: 'Jack',
    size: 'big',
    timeStamp: 1351913827415,
  },
  {
    location: 'Lviv',
    isDog: false,
    sex: 'female',
    age: 4,
    type: 'Mastiff English',
    color: 'brown',
    isVaccinated: false,
    description:
      'This is a beautiful example of a Mastiff English, known for its Mixed coat. At 4 years old, Dog 24 is not vaccinated and loves to play in Ukraine.',
    images: [
      'https://images.dog.ceo/breeds/greyhound-italian/n02091032_102.jpg',
      'https://images.dog.ceo/breeds/terrier-irish/n02093991_89.jpg',
      'https://images.dog.ceo/breeds/spaniel-blenheim/n02086646_371.jpg',
    ],
    name: 'Stella',
    size: 'small',
    timeStamp: 1214870157048,
  },
  {
    location: 'Kiev',
    isDog: true,
    sex: 'male',
    age: 5,
    type: 'Komondor',
    color: 'brown',
    isVaccinated: true,
    description:
      'This is a beautiful example of a Komondor, known for its Mixed coat. At 5 years old, Dog 25 is vaccinated and loves to play in Ukraine.',
    images: [
      'https://images.dog.ceo/breeds/terrier-irish/n02093991_89.jpg',
      'https://images.dog.ceo/breeds/spaniel-blenheim/n02086646_371.jpg',
      'https://images.dog.ceo/breeds/labradoodle/lola.jpg',
    ],
    name: 'Finn',
    size: 'medium',
    timeStamp: 996342941402,
  },
  {
    location: 'Kiev',
    isDog: false,
    sex: 'female',
    age: 6,
    type: 'Poodle Toy',
    color: 'mixed',
    isVaccinated: false,
    description:
      'This is a beautiful example of a Poodle Toy, known for its Mixed coat. At 6 years old, Dog 26 is not vaccinated and loves to play in Ukraine.',
    images: [
      'https://images.dog.ceo/breeds/spaniel-blenheim/n02086646_371.jpg',
      'https://images.dog.ceo/breeds/labradoodle/lola.jpg',
      'https://images.dog.ceo/breeds/kelpie/n02105412_715.jpg',
    ],
    name: 'Zoe',
    size: 'big',
    timeStamp: 1463229110798,
  },
  {
    location: 'Dnipro',
    isDog: true,
    sex: 'male',
    age: 7,
    type: 'Retriever Flatcoated',
    color: 'mixed',
    isVaccinated: true,
    description:
      'This is a beautiful example of a Retriever Flatcoated, known for its Mixed coat. At 7 years old, Dog 27 is vaccinated and loves to play in Ukraine.',
    images: [
      'https://images.dog.ceo/breeds/labradoodle/lola.jpg',
      'https://images.dog.ceo/breeds/kelpie/n02105412_715.jpg',
      'https://images.dog.ceo/breeds/shihtzu/n02086240_8812.jpg',
    ],
    name: 'Murphy',
    size: 'small',
    timeStamp: 1437876586117,
  },
  {
    location: 'Kiev',
    isDog: false,
    sex: 'female',
    age: 8,
    type: 'Papillon',
    color: 'mixed',
    isVaccinated: false,
    description:
      'This is a beautiful example of a Papillon, known for its Mixed coat. At 8 years old, Dog 28 is not vaccinated and loves to play in Ukraine.',
    images: [
      'https://images.dog.ceo/breeds/kelpie/n02105412_715.jpg',
      'https://images.dog.ceo/breeds/shihtzu/n02086240_8812.jpg',
      'https://images.dog.ceo/breeds/hound-blood/n02088466_12353.jpg',
    ],
    name: 'Lily',
    size: 'medium',
    timeStamp: 978885710190,
  },
  {
    location: 'Lviv',
    isDog: true,
    sex: 'male',
    age: 9,
    type: 'Mastiff English',
    color: 'white',
    isVaccinated: true,
    description:
      'This is a beautiful example of a Mastiff English, known for its Mixed coat. At 9 years old, Dog 29 is vaccinated and loves to play in Ukraine.',
    images: [
      'https://images.dog.ceo/breeds/shihtzu/n02086240_8812.jpg',
      'https://images.dog.ceo/breeds/hound-blood/n02088466_12353.jpg',
      'https://images.dog.ceo/breeds/puggle/IMG_095543.jpg',
    ],
    name: 'Leo',
    size: 'big',
    timeStamp: 1111569826843,
  },
  {
    location: 'Lviv',
    isDog: false,
    sex: 'female',
    age: 10,
    type: 'Komondor',
    color: 'brown',
    isVaccinated: false,
    description:
      'This is a beautiful example of a Komondor, known for its Mixed coat. At 10 years old, Dog 30 is not vaccinated and loves to play in Ukraine.',
    images: [
      'https://images.dog.ceo/breeds/hound-blood/n02088466_12353.jpg',
      'https://images.dog.ceo/breeds/puggle/IMG_095543.jpg',
      'https://images.dog.ceo/breeds/komondor/n02105505_1360.jpg',
    ],
    name: 'Ellie',
    size: 'small',
    timeStamp: 1170588127923,
  },
  {
    location: 'Dnipro',
    isDog: true,
    sex: 'male',
    age: 1,
    type: 'Poodle Toy',
    color: 'mixed',
    isVaccinated: true,
    description:
      'This is a beautiful example of a Poodle Toy, known for its Mixed coat. At 1 years old, Dog 31 is vaccinated and loves to play in Ukraine.',
    images: [
      'https://images.dog.ceo/breeds/puggle/IMG_095543.jpg',
      'https://images.dog.ceo/breeds/komondor/n02105505_1360.jpg',
      'https://images.dog.ceo/breeds/frise-bichon/7.jpg',
    ],
    name: 'Gus',
    size: 'medium',
    timeStamp: 1444331079659,
  },
  {
    location: 'Lviv',
    isDog: false,
    sex: 'female',
    age: 2,
    type: 'Retriever Flatcoated',
    color: 'black',
    isVaccinated: false,
    description:
      'This is a beautiful example of a Retriever Flatcoated, known for its Mixed coat. At 2 years old, Dog 32 is not vaccinated and loves to play in Ukraine.',
    images: [
      'https://images.dog.ceo/breeds/komondor/n02105505_1360.jpg',
      'https://images.dog.ceo/breeds/frise-bichon/7.jpg',
      'https://images.dog.ceo/breeds/terrier-patterdale/patterdale-terrier-1330018870tnN.jpg',
    ],
    name: 'Nala',
    size: 'big',
    timeStamp: 1426748021066,
  },
  {
    location: 'Kiev',
    isDog: true,
    sex: 'male',
    age: 3,
    type: 'Papillon',
    color: 'brown',
    isVaccinated: true,
    description:
      'This is a beautiful example of a Papillon, known for its Mixed coat. At 3 years old, Dog 33 is vaccinated and loves to play in Ukraine.',
    images: [
      'https://images.dog.ceo/breeds/frise-bichon/7.jpg',
      'https://images.dog.ceo/breeds/terrier-patterdale/patterdale-terrier-1330018870tnN.jpg',
      'https://images.dog.ceo/breeds/saluki/n02091831_3222.jpg',
    ],
    name: 'Hank',
    size: 'small',
    timeStamp: 1020390212742,
  },
  {
    location: 'Kharkiv',
    isDog: false,
    sex: 'female',
    age: 4,
    type: 'Mastiff English',
    color: 'mixed',
    isVaccinated: false,
    description:
      'This is a beautiful example of a Mastiff English, known for its Mixed coat. At 4 years old, Dog 34 is not vaccinated and loves to play in Ukraine.',
    images: [
      'https://images.dog.ceo/breeds/terrier-patterdale/patterdale-terrier-1330018870tnN.jpg',
      'https://images.dog.ceo/breeds/saluki/n02091831_3222.jpg',
      'https://images.dog.ceo/breeds/terrier-wheaten/n02098105_2639.jpg',
    ],
    name: 'Penny',
    size: 'medium',
    timeStamp: 978281425328,
  },
  {
    location: 'Dnipro',
    isDog: true,
    sex: 'male',
    age: 5,
    type: 'Komondor',
    color: 'mixed',
    isVaccinated: true,
    description:
      'This is a beautiful example of a Komondor, known for its Mixed coat. At 5 years old, Dog 35 is vaccinated and loves to play in Ukraine.',
    images: [
      'https://images.dog.ceo/breeds/saluki/n02091831_3222.jpg',
      'https://images.dog.ceo/breeds/terrier-wheaten/n02098105_2639.jpg',
      'https://images.dog.ceo/breeds/sheepdog-english/n02105641_2750.jpg',
    ],
    name: 'Milo',
    size: 'big',
    timeStamp: 1472377560737,
  },
  {
    location: 'Kiev',
    isDog: false,
    sex: 'female',
    age: 6,
    type: 'Poodle Toy',
    color: 'brown',
    isVaccinated: false,
    description:
      'This is a beautiful example of a Poodle Toy, known for its Mixed coat. At 6 years old, Dog 36 is not vaccinated and loves to play in Ukraine.',
    images: [
      'https://images.dog.ceo/breeds/terrier-wheaten/n02098105_2639.jpg',
      'https://images.dog.ceo/breeds/sheepdog-english/n02105641_2750.jpg',
      'https://images.dog.ceo/breeds/poodle-miniature/n02113712_171.jpg',
    ],
    name: 'Ruby',
    size: 'small',
    timeStamp: 1512219950396,
  },
  {
    location: 'Lviv',
    isDog: true,
    sex: 'male',
    age: 7,
    type: 'Retriever Flatcoated',
    color: 'mixed',
    isVaccinated: true,
    description:
      'This is a beautiful example of a Retriever Flatcoated, known for its Mixed coat. At 7 years old, Dog 37 is vaccinated and loves to play in Ukraine.',
    images: [
      'https://images.dog.ceo/breeds/sheepdog-english/n02105641_2750.jpg',
      'https://images.dog.ceo/breeds/poodle-miniature/n02113712_171.jpg',
      'https://images.dog.ceo/breeds/shihtzu/n02086240_5536.jpg',
    ],
    name: 'Zeus',
    size: 'medium',
    timeStamp: 1225158898993,
  },
  {
    location: 'Lviv',
    isDog: false,
    sex: 'female',
    age: 8,
    type: 'Papillon',
    color: 'brown',
    isVaccinated: false,
    description:
      'This is a beautiful example of a Papillon, known for its Mixed coat. At 8 years old, Dog 38 is not vaccinated and loves to play in Ukraine.',
    images: [
      'https://images.dog.ceo/breeds/poodle-miniature/n02113712_171.jpg',
      'https://images.dog.ceo/breeds/shihtzu/n02086240_5536.jpg',
      'https://images.dog.ceo/breeds/terrier-toy/n02087046_4401.jpg',
    ],
    name: 'Rosie',
    size: 'big',
    timeStamp: 1496977003846,
  },
  {
    location: 'Dnipro',
    isDog: true,
    sex: 'male',
    age: 9,
    type: 'Mastiff English',
    color: 'mixed',
    isVaccinated: true,
    description:
      'This is a beautiful example of a Mastiff English, known for its Mixed coat. At 9 years old, Dog 39 is vaccinated and loves to play in Ukraine.',
    images: [
      'https://images.dog.ceo/breeds/shihtzu/n02086240_5536.jpg',
      'https://images.dog.ceo/breeds/terrier-toy/n02087046_4401.jpg',
      'https://images.dog.ceo/breeds/spaniel-brittany/n02101388_2021.jpg',
    ],
    name: 'Louie',
    size: 'small',
    timeStamp: 1311166858536,
  },
  {
    location: 'Kiev',
    isDog: false,
    sex: 'female',
    age: 10,
    type: 'Komondor',
    color: 'white',
    isVaccinated: false,
    description:
      'This is a beautiful example of a Komondor, known for its Mixed coat. At 10 years old, Dog 40 is not vaccinated and loves to play in Ukraine.',
    images: [
      'https://images.dog.ceo/breeds/terrier-toy/n02087046_4401.jpg',
      'https://images.dog.ceo/breeds/spaniel-brittany/n02101388_2021.jpg',
      'https://images.dog.ceo/breeds/chihuahua/n02085620_13151.jpg',
    ],
    name: 'Mia',
    size: 'medium',
    timeStamp: 1072886074778,
  },
  {
    location: 'Kiev',
    isDog: true,
    sex: 'male',
    age: 1,
    type: 'Poodle Toy',
    color: 'brown',
    isVaccinated: true,
    description:
      'This is a beautiful example of a Poodle Toy, known for its Mixed coat. At 1 years old, Dog 41 is vaccinated and loves to play in Ukraine.',
    images: [
      'https://images.dog.ceo/breeds/spaniel-brittany/n02101388_2021.jpg',
      'https://images.dog.ceo/breeds/chihuahua/n02085620_13151.jpg',
      'https://images.dog.ceo/breeds/corgi-cardigan/n02113186_11400.jpg',
    ],
    name: 'Jasper',
    size: 'big',
    timeStamp: 1252422806967,
  },
  {
    location: 'Dnipro',
    isDog: false,
    sex: 'female',
    age: 2,
    type: 'Retriever Flatcoated',
    color: 'white',
    isVaccinated: false,
    description:
      'This is a beautiful example of a Retriever Flatcoated, known for its Mixed coat. At 2 years old, Dog 42 is not vaccinated and loves to play in Ukraine.',
    images: [
      'https://images.dog.ceo/breeds/chihuahua/n02085620_13151.jpg',
      'https://images.dog.ceo/breeds/corgi-cardigan/n02113186_11400.jpg',
      'https://images.dog.ceo/breeds/malamute/n02110063_6746.jpg',
    ],
    name: 'Roxy',
    size: 'small',
    timeStamp: 1355427065628,
  },
  {
    location: 'Lviv',
    isDog: true,
    sex: 'male',
    age: 3,
    type: 'Papillon',
    color: 'brown',
    isVaccinated: true,
    description:
      'This is a beautiful example of a Papillon, known for its Mixed coat. At 3 years old, Dog 43 is vaccinated and loves to play in Ukraine.',
    images: [
      'https://images.dog.ceo/breeds/corgi-cardigan/n02113186_11400.jpg',
      'https://images.dog.ceo/breeds/malamute/n02110063_6746.jpg',
      'https://images.dog.ceo/breeds/cattledog-australian/IMG_2432.jpg',
    ],
    name: 'Oscar',
    size: 'medium',
    timeStamp: 1610272991399,
  },
  {
    location: 'Kharkiv',
    isDog: false,
    sex: 'female',
    age: 4,
    type: 'Mastiff English',
    color: 'brown',
    isVaccinated: false,
    description:
      'This is a beautiful example of a Mastiff English, known for its Mixed coat. At 4 years old, Dog 44 is not vaccinated and loves to play in Ukraine.',
    images: [
      'https://images.dog.ceo/breeds/malamute/n02110063_6746.jpg',
      'https://images.dog.ceo/breeds/cattledog-australian/IMG_2432.jpg',
      'https://images.dog.ceo/breeds/retriever-flatcoated/n02099267_3490.jpg',
    ],
    name: 'Gracie',
    size: 'big',
    timeStamp: 1132883501916,
  },
  {
    location: 'Lviv',
    isDog: true,
    sex: 'male',
    age: 5,
    type: 'Komondor',
    color: 'mixed',
    isVaccinated: true,
    description:
      'This is a beautiful example of a Komondor, known for its Mixed coat. At 5 years old, Dog 45 is vaccinated and loves to play in Ukraine.',
    images: [
      'https://images.dog.ceo/breeds/cattledog-australian/IMG_2432.jpg',
      'https://images.dog.ceo/breeds/retriever-flatcoated/n02099267_3490.jpg',
      'https://images.dog.ceo/breeds/groenendael/n02105056_3348.jpg',
    ],
    name: 'Winston',
    size: 'small',
    timeStamp: 1585338028863,
  },
  {
    location: 'Lviv',
    isDog: false,
    sex: 'female',
    age: 6,
    type: 'Poodle Toy',
    color: 'brown',
    isVaccinated: false,
    description:
      'This is a beautiful example of a Poodle Toy, known for its Mixed coat. At 6 years old, Dog 46 is not vaccinated and loves to play in Ukraine.',
    images: [
      'https://images.dog.ceo/breeds/retriever-flatcoated/n02099267_3490.jpg',
      'https://images.dog.ceo/breeds/groenendael/n02105056_3348.jpg',
      'https://images.dog.ceo/breeds/poodle-medium/PXL_20210220_100624962.jpg',
    ],
    name: 'Coco',
    size: 'medium',
    timeStamp: 1272079292805,
  },
  {
    location: 'Lviv',
    isDog: true,
    sex: 'male',
    age: 7,
    type: 'Retriever Flatcoated',
    color: 'brown',
    isVaccinated: true,
    description:
      'This is a beautiful example of a Retriever Flatcoated, known for its Mixed coat. At 7 years old, Dog 47 is vaccinated and loves to play in Ukraine.',
    images: [
      'https://images.dog.ceo/breeds/groenendael/n02105056_3348.jpg',
      'https://images.dog.ceo/breeds/poodle-medium/PXL_20210220_100624962.jpg',
      'https://images.dog.ceo/breeds/spaniel-irish/n02102973_3933.jpg',
    ],
    name: 'Sammy',
    size: 'big',
    timeStamp: 1031863693587,
  },
  {
    location: 'Kiev',
    isDog: false,
    sex: 'female',
    age: 8,
    type: 'Papillon',
    color: 'black',
    isVaccinated: false,
    description:
      'This is a beautiful example of a Papillon, known for its Mixed coat. At 8 years old, Dog 48 is not vaccinated and loves to play in Ukraine.',
    images: [
      'https://images.dog.ceo/breeds/poodle-medium/PXL_20210220_100624962.jpg',
      'https://images.dog.ceo/breeds/spaniel-irish/n02102973_3933.jpg',
      'https://images.dog.ceo/breeds/mexicanhairless/n02113978_3092.jpg',
    ],
    name: 'Lulu',
    size: 'small',
    timeStamp: 1261063985387,
  },
  {
    location: 'Lviv',
    isDog: true,
    sex: 'male',
    age: 9,
    type: 'Mastiff English',
    color: 'black',
    isVaccinated: true,
    description:
      'This is a beautiful example of a Mastiff English, known for its Mixed coat. At 9 years old, Dog 49 is vaccinated and loves to play in Ukraine.',
    images: [
      'https://images.dog.ceo/breeds/spaniel-irish/n02102973_3933.jpg',
      'https://images.dog.ceo/breeds/mexicanhairless/n02113978_3092.jpg',
      'https://images.dog.ceo/breeds/spaniel-irish/n02102973_3405.jpg',
    ],
    name: 'Teddy',
    size: 'medium',
    timeStamp: 1031268403832,
  },
  {
    location: 'Kharkiv',
    isDog: false,
    sex: 'female',
    age: 10,
    type: 'Komondor',
    color: 'black',
    isVaccinated: false,
    description:
      'This is a beautiful example of a Komondor, known for its Mixed coat. At 10 years old, Dog 50 is not vaccinated and loves to play in Ukraine.',
    images: [
      'https://images.dog.ceo/breeds/mexicanhairless/n02113978_3092.jpg',
      'https://images.dog.ceo/breeds/spaniel-irish/n02102973_3405.jpg',
      'https://images.dog.ceo/breeds/poodle-medium/WhatsApp_Image_2022-08-06_at_4.48.38_PM.jpg',
    ],
    name: 'Piper',
    size: 'big',
    timeStamp: 1048759881924,
  },
];
